framework: mocha

postMerge:
  env:
      NODE_ENV: test
  pattern:
    - "packages/**/*.test.{js,ts,tsx}"
    - "docs/**/*.test.{js,ts,tsx}"
    - "scripts/**/*.test.{js,ts,tsx}"
    - "test/utils/**/*.test.{js,ts,tsx}"

preMerge:
  env:
    NODE_ENV: test
  pattern:
    - "packages/**/*.test.{js,ts,tsx}"
    - "docs/**/*.test.{js,ts,tsx}"
    - "scripts/**/*.test.{js,ts,tsx}"
    - "test/utils/**/*.test.{js,ts,tsx}"
      
preRun:
     command:
        - yarn

configFile: ".mocharc.js"
version: 1.0.0
