framework: mocha

postMerge:
  env:
      NODE_ENV: test
  pattern:
    - "**/*.test.{js,ts,tsx}"

preMerge:
  env:
    NODE_ENV: test
  pattern:
    - "**/*.test.{js,ts,tsx}"
preRun:
     command:
        - yarn

smartRun: false

configFile: ".mocharc.js"
version: 1.0.0
